{"uuid": "60e9e4ac-1d65-4fd7-b911-e762d8f01121", "children": ["f99de60e-f29c-4974-a67b-4edc15be90fe"], "befores": [{"name": "create_and_remove_user", "status": "passed", "start": 1740151208419, "stop": 1740151208714}], "afters": [{"name": "create_and_remove_user::0", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='stellarburgers.nomoreparties.site', port=443): Max retries exceeded with url: /auth/user (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1051d65d0>, 'Connection to stellarburgers.nomoreparties.site timed out. (connect timeout=None)'))\n", "trace": "  File \"/Users/grigorysevryukov/projects/Diplom_3/.venv/lib/python3.13/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"/Users/grigorysevryukov/projects/Diplom_3/.venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n    ~~~~^^^^\n  File \"/Users/grigorysevryukov/projects/Diplom_3/conftest.py\", line 32, in create_and_remove_user\n    requests.delete(UPDATE_USER_INFO_URL, headers=auth_headers, data=delete_body)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/grigorysevryukov/projects/Diplom_3/.venv/lib/python3.13/site-packages/requests/api.py\", line 157, in delete\n    return request(\"delete\", url, **kwargs)\n  File \"/Users/grigorysevryukov/projects/Diplom_3/.venv/lib/python3.13/site-packages/requests/api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/grigorysevryukov/projects/Diplom_3/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/Users/grigorysevryukov/projects/Diplom_3/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n  File \"/Users/grigorysevryukov/projects/Diplom_3/.venv/lib/python3.13/site-packages/requests/adapters.py\", line 688, in send\n    raise ConnectTimeout(e, request=request)\n"}, "start": 1740151209234, "stop": 1740151217303}], "start": 1740151208419, "stop": 1740151217303}